---
- name: test if y_presets is set correctly
  assert:
    that:
      - y_presets | length > 0
  when:
    - y_presets is defined


- name: test if item in y_presets is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.name in ["monochrome"]
  loop: "{{ y_presets }}"
  when:
    - y_presets is defined

- name: test if y_import_from is set correctly
  assert:
    that:
      - y_import_from is defined
      - y_import_from | length > 0

- name: test if y_export_to is set correctly
  assert:
    that:
      - y_export_to is defined
      - y_export_to | length > 0
