---
- name: save the year
  shell: set -o pipefail ; {{ y_exiftool_binary }} {{ image.path }} -d "%Y" | grep "Create Date" | awk '{print $NF}'
  args:
    creates: nothing
    executable: /bin/bash
  register: year
  changed_when: no
  check_mode: no

- name: save the month
  shell: set -o pipefail ; {{ y_exiftool_binary }} {{ image.path }} -d "%m" | grep "Create Date" | awk '{print $NF}'
  args:
    creates: nothing
    executable: /bin/bash
  register: month
  changed_when: no
  check_mode: no

- name: save the day
  shell: set -o pipefail ; {{ y_exiftool_binary }} {{ image.path }} -d "%d" | grep "Create Date" | awk '{print $NF}'
  args:
    creates: nothing
    executable: /bin/bash
  register: day
  changed_when: no
  check_mode: no

- name: ensure directory structure exists
  file:
    path: "{{ y_export_path }}"
    state: directory

- name: process images
  block:
    - name: processing {{ image.path | basename }}
      shell: dcraw -c "{{ y_command_options[y_preset] }}" "{{ image.path }}" > "{{ y_export_path }}/{{ (image.path | basename | splitext)[0] }}.pgm"
      args:
        creates: "{{ y_export_path }}/{{ (image.path | basename | splitext)[0] }}.pgm"

    - name: copying processed image back
      fetch:
        src: "{{ y_export_path }}/{{ (image.path | basename | splitext)[0] }}.pgm"
        dest: "{{ y_export_to }}/{{ (image.path | basename | splitext)[0] }}.pgm"
        flat: yes
      when:
        - y_convert_images | bool

- name: copying unprocessed image back
  fetch:
    src: "{{ y_export_path }}/{{ (image.path | basename }}"
    dest: "{{ y_export_to }}"
    flat: yes
  when:
    - not y_convert_images | bool
