---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel

  tasks:
    - name: create /data
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /data
        - /data/in
        - /data/out

    - name: copy samples files to /data
      copy:
        src: "{{ item }}"
        dest: /data/in
      with_items:
        - sample.RAF
