---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-y
      y_import_from: /data/in
      y_export_to: files/out
      y_presets:
        - name: monochrome
