---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel

  tasks:
    - name: create directories in container
      file:
        path: "{{ item }}"
        state: directory
        mode: "0644"
      with_items:
        - /data
        - /data/in
        - /data/out

    - name: copy samples files to /data/in
      copy:
        src: in/
        dest: /data/in
        mode: "0644"
